/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import aplicacion.FachadaAplicacion;
import aplicacion.Cita;
import javax.swing.table.*;
/**
 *
 * @author alumnogreibd
 */
public class VCitasP extends javax.swing.JFrame {
    private FachadaAplicacion fa;
    /**
     * Creates new form VCitasP
     */
    public VCitasP(FachadaAplicacion fa) {
        this.setContentPane(new Fondo());
        initComponents();
        this.fa = fa;
        ModeloTablaCitasP mTCitasP;
        mTCitasP = new ModeloTablaCitasP();
        tablaCitas.setModel(mTCitasP);
        mTCitasP.setFilas(fa.consultarCitasP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaSucursal = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        etiquetaCitas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnDenegar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaSucursal.setText("Sucursal:");

        campoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        etiquetaCitas.setText("Citas:");

        tablaCitas.setModel(new ModeloTablaCitasP());
        jScrollPane1.setViewportView(tablaCitas);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnDenegar.setText("Denegar");
        btnDenegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenegarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCitas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaSucursal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDenegar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSucursal)
                    .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(26, 26, 26)
                .addComponent(etiquetaCitas)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnAceptar)
                        .addGap(39, 39, 39)
                        .addComponent(btnDenegar)))
                .addGap(133, 133, 133))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarCitas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        ModeloTablaCitasP mTCitasP;
        mTCitasP = (ModeloTablaCitasP) tablaCitas.getModel();
        fa.aceptarCita(mTCitasP.obtenerCita(tablaCitas.getSelectedRow()));
        buscarCitas();
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnDenegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenegarActionPerformed
        
        ModeloTablaCitasP mTCitasP;
        mTCitasP = (ModeloTablaCitasP) tablaCitas.getModel();
        fa.denegarCita(mTCitasP.obtenerCita(tablaCitas.getSelectedRow()));
        buscarCitas();
        
    }//GEN-LAST:event_btnDenegarActionPerformed

    public void buscarCitas(){
        
        ModeloTablaCitasP mTCitasP;
        mTCitasP = (ModeloTablaCitasP) tablaCitas.getModel();
        
        
        if(!campoBuscar.getText().isBlank()){
            try{
                mTCitasP.setFilas(fa.buscarCitasP(Integer.parseInt(campoBuscar.getText())));
            }catch(NumberFormatException e){
                fa.muestraExcepcion(e.getMessage());
            }
            
        }else
            mTCitasP.setFilas(fa.consultarCitasP());
        if(mTCitasP.getRowCount()>0){
            tablaCitas.setRowSelectionInterval(0,0);
            btnAceptar.setEnabled(true);
            btnDenegar.setEnabled(true);
        }else{
            btnAceptar.setEnabled(false);
            btnDenegar.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDenegar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel etiquetaCitas;
    private javax.swing.JLabel etiquetaSucursal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables
}
