/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Cita;
import aplicacion.Cliente;
import aplicacion.FachadaAplicacion;
import aplicacion.Personal;
import aplicacion.Sucursal;
import aplicacion.Usuario;
import aplicacion.Voluntario;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author alumnogreibd
 */
public class VCitasCliente extends javax.swing.JFrame {

    /**
     * Creates new form VCitasCliente
     */
    private aplicacion.FachadaAplicacion fa;
    private Usuario usuario;
    
    public VCitasCliente(aplicacion.FachadaAplicacion fa, Usuario usuario) {
        this.fa = fa;
        this.usuario = usuario;
        this.setContentPane(new Fondo());
        initComponents();
        
        ModeloTablaCitasCliente mtcc = new ModeloTablaCitasCliente();
        tbCitas.setModel(mtcc);
        tbCitas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbCitas.getSelectionModel().addListSelectionListener((lse) -> {
            int index = tbCitas.getSelectedRow();
            if(index < 0)
                return;
            
            Cita cita = mtcc.obtenerCita(index);
            cbSucursal.setSelectedItem(cita.getSucursal());//????
            textFecha.setText(cita.getFechaCita().toString());
            
        });
        
        List<Sucursal> listaSucursales = fa.listaSucursales();
        for(Sucursal s: listaSucursales)
            cbSucursal.addItem(s);
        
        List<Cita> listaCitas = fa.buscarCitasCliente(usuario.getDni());
        mtcc.setFilas(listaCitas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCitas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbSucursal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textFecha = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mis citas:");

        tbCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCitas);

        jLabel2.setText("Sucursal:");

        jLabel3.setText("Fecha:");

        textFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        textFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(cbSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(textFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(41, 41, 41))))
                    .addComponent(jLabel1))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addGap(176, 176, 176))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        cbSucursal.setSelectedIndex(0);
        Date d = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        textFecha.setText(formatter.format(d));
        tbCitas.clearSelection();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int index = tbCitas.getSelectedRow();
        if(index < 0) {
            try {
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                Date parsed = format.parse(textFecha.getText());
                java.sql.Date sql = new java.sql.Date(parsed.getTime());
                Date d = new Date();
                Cita c = new Cita(new java.sql.Date(d.getTime()), sql, null, ((Sucursal)cbSucursal.getSelectedItem()), usuario.getDni());
                
                int result = fa.insertarCita(c);
                if(result > 0) {
                    ((ModeloTablaCitasCliente)tbCitas.getModel()).addCita(c);
                }
            } catch (ParseException ex) {
                Logger.getLogger(VCitasCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                Cita oldCita = ((ModeloTablaCitasCliente)tbCitas.getModel()).obtenerCita(index);
                Cita newCita = new Cita(oldCita);
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                Date parsed = format.parse(textFecha.getText());
                java.sql.Date sql = new java.sql.Date(parsed.getTime());
                newCita.setFechaCita(sql);
                newCita.setSucursal(((Sucursal)cbSucursal.getSelectedItem()));
                newCita.setCancelado(null);
            
                int result = fa.actualizarCita(oldCita, newCita);
                if(result > 0) {
                    ((ModeloTablaCitasCliente)tbCitas.getModel()).sustituirCita(index, newCita);
                }
             } catch (ParseException ex) {
                Logger.getLogger(VCitasCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int index = tbCitas.getSelectedRow();
        if(index < 0)
            return;
        
        Cita c = ((ModeloTablaCitasCliente)tbCitas.getModel()).obtenerCita(index);
        int result = fa.borrarCita(c);
        
        if(result > 0)
            ((ModeloTablaCitasCliente)tbCitas.getModel()).eliminarCita(index);
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Sucursal> cbSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCitas;
    private javax.swing.JFormattedTextField textFecha;
    // End of variables declaration//GEN-END:variables
}
