/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import aplicacion.Sucursal;
import aplicacion.Personal;
import aplicacion.FachadaAplicacion;
import java.awt.*;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JPanel;

/**
 *
 * @author alumnogreibd
 */
public class VGestionSucursales extends javax.swing.JDialog {
    Personal usuario;
    boolean nuevo;
    FachadaAplicacion fa;
     private Image backgroundImage;
    
    /**
     * Creates new form VGestionSucursales
     */
    public VGestionSucursales(Personal usuario, FachadaAplicacion fa) {
        this.setContentPane(new Fondo());
        initComponents();
        
        this.usuario=usuario;
        this.fa=fa;
        //this.setContentPane(fondo);
        
        nuevo=false;
        buscarSucursales();
      
        
    }
    
   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSucursales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        municipioBuscarText = new javax.swing.JTextField();
        numSucursalBuscarText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        municipioText = new javax.swing.JTextField();
        numSucursalText = new javax.swing.JTextField();
        guardarbtn = new javax.swing.JButton();
        nuevobtn = new javax.swing.JButton();
        borrarbtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        buscarbtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 449), new java.awt.Dimension(0, 449), new java.awt.Dimension(32767, 449));

        setTitle("Gestion Sucursales");
        setBackground(new java.awt.Color(230, 225, 211));
        setName("Gestion Sucursales"); // NOI18N
        setResizable(false);

        jLabel1.setText("numSucursal:");

        jScrollPane1.setBackground(new java.awt.Color(174, 190, 161));

        tablaSucursales.setModel(new ModeloTablaSucursales());
        tablaSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarSucursal(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSucursales);

        jLabel2.setText("municipio:");

        municipioBuscarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioBuscarTextActionPerformed(evt);
            }
        });

        numSucursalBuscarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSucursalBuscarTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Municipio:");

        jLabel4.setText("numSucursal:");

        guardarbtn.setText("Guardar");
        guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtnActionPerformed(evt);
            }
        });

        nuevobtn.setText("Nuevo");
        nuevobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobtnActionPerformed(evt);
            }
        });

        borrarbtn.setText("Borrar");
        borrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbtnActionPerformed(evt);
            }
        });

        jButton5.setText("tiendas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buscarbtn.setText("Buscar");
        buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numSucursalBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(municipioBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numSucursalText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(borrarbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numSucursalBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(municipioBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarbtn))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(municipioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(guardarbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numSucursalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(nuevobtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(borrarbtn)))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numSucursalBuscarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSucursalBuscarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSucursalBuscarTextActionPerformed

    private void municipioBuscarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioBuscarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioBuscarTextActionPerformed

    private void nuevobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobtnActionPerformed
        // TODO add your handling code here:
        tablaSucursales.clearSelection();
        this.nuevo=true;
        borrarbtn.setEnabled(false);
        municipioText.setText("");
        numSucursalText.setText("");
    }//GEN-LAST:event_nuevobtnActionPerformed

    private void buscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtnActionPerformed
        // TODO add your handling code here:
        buscarSucursales();
    }//GEN-LAST:event_buscarbtnActionPerformed

    private void seleccionarSucursal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarSucursal
        // TODO add your handling code here:
        ConfigurarInfoSucursalSelecionada();
    }//GEN-LAST:event_seleccionarSucursal

    private void borrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbtnActionPerformed
        // TODO add your handling code here:
        fa.eliminarSucursal(Integer.parseInt(numSucursalText.getText()));
        buscarSucursales();
    }//GEN-LAST:event_borrarbtnActionPerformed

    private void guardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtnActionPerformed
        // TODO add your handling code here:
        if (nuevo==true){
            fa.nuevaSucursal(Integer.parseInt(numSucursalText.getText()),municipioText.getText());
           
        }
        else{
            ModeloTablaSucursales m;
            m=(ModeloTablaSucursales) tablaSucursales.getModel();
            fa.actualizarSucursal((int)m.getValueAt(tablaSucursales.getSelectedRow(),0),Integer.parseInt(numSucursalText.getText()),municipioText.getText());
        }
         buscarSucursales();
        
    }//GEN-LAST:event_guardarbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         ModeloTablaSucursales m;
        m=(ModeloTablaSucursales) tablaSucursales.getModel();
        fa.abrirVTiendas((int)m.getValueAt(tablaSucursales.getSelectedRow(),0));
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarbtn;
    private javax.swing.JButton buscarbtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton guardarbtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField municipioBuscarText;
    private javax.swing.JTextField municipioText;
    private javax.swing.JButton nuevobtn;
    private javax.swing.JTextField numSucursalBuscarText;
    private javax.swing.JTextField numSucursalText;
    private javax.swing.JTable tablaSucursales;
    // End of variables declaration//GEN-END:variables


    public void ConfigurarInfoSucursalSelecionada(){
        this.nuevo=false;
        borrarbtn.setEnabled(true);
        ModeloTablaSucursales m;
        m=(ModeloTablaSucursales) tablaSucursales.getModel();
        municipioText.setText((String)m.getValueAt(tablaSucursales.getSelectedRow(),1));
        numSucursalText.setText(String.valueOf((Integer) m.getValueAt(tablaSucursales.getSelectedRow(),0)));
}
    
 public void buscarSucursales(){
        ModeloTablaSucursales m;
        m=(ModeloTablaSucursales) tablaSucursales.getModel();
        m.setFilas(fa.obtenerSucursales(municipioBuscarText.getText(), numSucursalBuscarText.getText()));
        
        if (m.getRowCount()> 0) {
            tablaSucursales.setRowSelectionInterval(0, 0);
            ConfigurarInfoSucursalSelecionada();
            guardarbtn.setEnabled(true);
            borrarbtn.setEnabled(true);
        }
        else {
            this.nuevo=false;
            numSucursalText.setText("");
            municipioText.setText("");
            guardarbtn.setEnabled(false);
            borrarbtn.setEnabled(false);
        }
    }
    


}
