/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import aplicacion.Usuario;
import aplicacion.FachadaAplicacion;

/**
 *
 * @author alumnogreibd
 */
public class VInicio extends javax.swing.JFrame {
    private FondoPanel fondo;// = new FondoPanel();
    private FachadaAplicacion fa;
    private Usuario usuario;
    /**
     * Creates new form VInicio
     */
    public VInicio(FachadaAplicacion fa) {
        this.fa=fa;
        fondo = new FondoPanel();
        this.setContentPane(fondo);
        initComponents();
        
    }
    
    public void setusuario(Usuario usuario){
        this.usuario=usuario;
        etiquetaBienvenida.setText("Bienvenid@ " + usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new java.awt.Panel();
        etiquetaBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitulo.setBackground(new java.awt.Color(204, 204, 204));

        etiquetaBienvenida.setBackground(new java.awt.Color(204, 204, 204));
        etiquetaBienvenida.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        etiquetaBienvenida.setText("BIENVENID@");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(etiquetaBienvenida)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(etiquetaBienvenida)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    class FondoPanel extends JPanel{
        private Image image;
        
        @Override
        public void paint(Graphics g){
            image = new ImageIcon(getClass().getResource("/images/fondo2.png")).getImage();
            
            g.drawImage(image,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaBienvenida;
    private java.awt.Panel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
