/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import aplicacion.FachadaAplicacion;
import aplicacion.Tarea;
import aplicacion.Usuario;
import aplicacion.Voluntario;
import java.awt.Color;
import javax.swing.table.*;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author alumnogreibd
 */
public class VNuevaTareaV extends javax.swing.JDialog {
    private FachadaAplicacion fa;
    Voluntario voluntario;
    VTareasV parent;
    /**
     * Creates new form VNuevaTareaV
     */
    public VNuevaTareaV(java.awt.Frame parent, boolean modal,FachadaAplicacion fa, Voluntario voluntario) {
        super(parent,modal);
        getContentPane().setBackground(new Color(200,199,196));
        this.parent=(VTareasV)parent;
        initComponents();
        this.fa=fa;
        this.voluntario=voluntario;
        buscarTareasLibres();
         addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                ((VTareasV)parent).buscarTareas();
                dispose(); // Cierra el diálogo
                
            }
        });
        
        
    }
    
    public void buscarTareasLibres(){
        ModeloTablaTareas mtTareas;
        mtTareas = new ModeloTablaTareas();
        tablaTareasLibres.setModel(mtTareas);
        mtTareas.setFilas(fa.consultarTareasLibres());
        if(mtTareas.getRowCount()>0){
            tablaTareasLibres.setRowSelectionInterval(0,0);
        }else{
            btnAceptar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTareasLibres = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaTareasLibres.setModel(new ModeloTablaTareas());
        tablaTareasLibres.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaTareasLibres);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAceptar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        parent.buscarTareas();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        fa.aceptarTarea(voluntario, ((ModeloTablaTareas)tablaTareasLibres.getModel()).obtenerTarea(tablaTareasLibres.getSelectedRow()));
        buscarTareasLibres();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTareasLibres;
    // End of variables declaration//GEN-END:variables
}
