/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Cliente;
import aplicacion.Evento;
import aplicacion.FachadaAplicacion;
import aplicacion.Personal;
import aplicacion.Usuario;
import java.util.List;
import javax.swing.ListSelectionModel;

/**
 *
 * @author alumnogreibd
 */
public class VParticiparEvento extends javax.swing.JFrame {
    aplicacion.FachadaAplicacion fa;
    Usuario usuario;
    /**
     * Creates new form VParticiparEvento
     */
    public VParticiparEvento(aplicacion.FachadaAplicacion fa, Usuario usuario) {
        this.fa = fa;
        this.usuario = usuario;
        this.setContentPane(new Fondo());
        initComponents();
        
        ModeloTablaParticiparEvento mtpe = new ModeloTablaParticiparEvento();
        tbEventos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbEventos.setModel(mtpe);
        tbEventos.getSelectionModel().addListSelectionListener((lse) -> {
            int index = tbEventos.getSelectedRow();
            if(index < 0)
                return;
            
            Evento evt = mtpe.obtenerEvento(index);
            textDescription.setText(evt.getDescripcion());
            
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbEventos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textNombreB = new javax.swing.JTextField();
        cbParticipa = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnParticipar = new javax.swing.JButton();
        Anular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbEventos);

        jLabel1.setText("Nombre:");

        cbParticipa.setText("Participa");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        textDescription.setEditable(false);
        textDescription.setColumns(20);
        textDescription.setLineWrap(true);
        textDescription.setRows(5);
        jScrollPane2.setViewportView(textDescription);

        jLabel2.setText("Descripción:");

        btnParticipar.setText("Participar");
        btnParticipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParticiparActionPerformed(evt);
            }
        });

        Anular.setText("Anular \nparticipación");
        Anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbParticipa)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Anular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnParticipar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbParticipa)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnParticipar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Anular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        List<Evento> eventos = fa.listarEventosUsuario(textNombreB.getText(), cbParticipa.isSelected(), usuario);
        
        ((ModeloTablaParticiparEvento) tbEventos.getModel()).setFilas(eventos);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticiparActionPerformed
        int index = tbEventos.getSelectedRow();
            if(index < 0)
                return;
        
        Evento ev =  ((ModeloTablaParticiparEvento) tbEventos.getModel()).obtenerEvento(index);
        int resultado = fa.participar(usuario, ev);
        if(resultado > 0) {
            ev.setParticipacionActual(true);
            ((ModeloTablaParticiparEvento) tbEventos.getModel()).sustituirEvento(index, ev);
        }
    }//GEN-LAST:event_btnParticiparActionPerformed

    private void AnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnularActionPerformed
        int index = tbEventos.getSelectedRow();
            if(index < 0)
                return;
        
        Evento ev =  ((ModeloTablaParticiparEvento) tbEventos.getModel()).obtenerEvento(index);
        int resultado = fa.anularParticipacion(usuario, ev);
        if(resultado > 0) {
            ev.setParticipacionActual(false);
            ((ModeloTablaParticiparEvento) tbEventos.getModel()).sustituirEvento(index, ev);
        }
    }//GEN-LAST:event_AnularActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anular;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnParticipar;
    private javax.swing.JCheckBox cbParticipa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbEventos;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textNombreB;
    // End of variables declaration//GEN-END:variables
}
