/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;
import aplicacion.Usuario;
import aplicacion.Personal;
import aplicacion.Voluntario;
import aplicacion.Cliente;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author basesdatos
 */
public class VPrincipal extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    Usuario usuario;
    
    /** Creates new form VPrincipal */
    public VPrincipal(aplicacion.FachadaAplicacion fa, Usuario usuario) {
        this.fa=fa;
        this.usuario= usuario;
        
        getContentPane().setBackground(new Color(190,184,171));
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
        VInicio inicio=new VInicio(fa);
        jTabbedPane1.addTab("Inicio",inicio.getContentPane());
        if (usuario instanceof Personal){
            VGestionSucursales sucursales=new VGestionSucursales((Personal)usuario, fa);
            VUsuarios vusuarios = new VUsuarios(fa, usuario);
            VCitasP vcitasp=new VCitasP(fa);
            VParticiparEvento participarevento= new VParticiparEvento(fa, usuario);
            jTabbedPane1.addTab("Sucursales",sucursales.getContentPane());
            jTabbedPane1.addTab("Usuarios",vusuarios.getContentPane());
            jTabbedPane1.addTab("Citas",vcitasp.getContentPane());
            jTabbedPane1.addTab("Eventos",participarevento.getContentPane());
        
        }
        else if (usuario instanceof Voluntario){
            
            VTareasV tareas=new VTareasV (fa, usuario);
            jTabbedPane1.addTab("Tareas",tareas.getContentPane());
            
        }
        else if (usuario instanceof Cliente){
            VCitasCliente citascliente=new VCitasCliente( fa, usuario);
            VParticiparEvento participarevento= new VParticiparEvento(fa, usuario);
            VComprar comprar=new VComprar(fa,usuario);
            jTabbedPane1.addTab("Eventos",participarevento.getContentPane());
            jTabbedPane1.addTab("Citas",citascliente.getContentPane());
            jTabbedPane1.addTab("Comprar",comprar.getContentPane());
        }
      
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setTitle("Biblioteca de Informática");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(btnSalir))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables



}
