/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import aplicacion.FachadaAplicacion;
import aplicacion.Tarea;
import aplicacion.Usuario;
import aplicacion.Voluntario;
import javax.swing.table.*;

/**
 *
 * @author alumnogreibd
 */
public class VTareasV extends javax.swing.JFrame {
    private FachadaAplicacion fa;
    private Usuario usuario;
    /**
     * Creates new form VTareasV
     */
    public VTareasV(FachadaAplicacion fa, Usuario usuario) {
        this.setContentPane(new Fondo());
        initComponents();
        this.fa = fa;
        this.usuario = usuario;
        buscarTareas();
    }
    
   
    
    private void campoDescripcion(){
        ModeloTablaTareas mtTareas;
        mtTareas = (ModeloTablaTareas)tablaTareas.getModel();
        Descripcion.setText(mtTareas.obtenerTarea(tablaTareas.getSelectedRow()).getDescripcion());
    }
    
    public void buscarTareas(){
        ModeloTablaTareas mtTareas;
        mtTareas = new ModeloTablaTareas();
        tablaTareas.setModel(mtTareas);
        mtTareas.setFilas(fa.consultarTareasVoluntario((Voluntario) this.usuario));
        if(mtTareas.getRowCount()>0){
            tablaTareas.setRowSelectionInterval(0,0);
            btnFichar.setEnabled(true);
            btnCancelar.setEnabled(true);
        }else{
            btnFichar.setEnabled(false);
            btnCancelar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        etiquetaTareas = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFichar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaDescripcion.setText("Descripcion:");

        tablaTareas.setModel(new ModeloTablaTareas());
        tablaTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaTareasMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaTareasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTareas);

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        Descripcion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Descripcion);

        etiquetaTareas.setText("Mis tareas:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFichar.setText("Fichar");
        btnFichar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etiquetaTareas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(etiquetaDescripcion)
                                    .addGap(154, 154, 154))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFichar)
                        .addGap(120, 120, 120)))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(etiquetaTareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnCancelar)
                    .addComponent(btnFichar))
                .addGap(253, 253, 253))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTareasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTareasMousePressed
        campoDescripcion();
    }//GEN-LAST:event_tablaTareasMousePressed

    private void tablaTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTareasMouseEntered
        
        campoDescripcion();
        
        
    }//GEN-LAST:event_tablaTareasMouseEntered

    private void btnFicharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicharActionPerformed
        if(( (ModeloTablaTareas) tablaTareas.getModel()).getRowCount() < 1){
            btnFichar.setEnabled(false);
            return;
        }
        fa.ficharTarea(( (ModeloTablaTareas) tablaTareas.getModel()).obtenerTarea(tablaTareas.getSelectedRow()), (Voluntario) usuario);
        buscarTareas();
    }//GEN-LAST:event_btnFicharActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(( (ModeloTablaTareas) tablaTareas.getModel()).getRowCount() < 1){
            btnCancelar.setEnabled(false);
            return;
        }
        fa.cancelarTarea(( (ModeloTablaTareas) tablaTareas.getModel()).obtenerTarea(tablaTareas.getSelectedRow()), (Voluntario) usuario);
        buscarTareas();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        fa.nuevaTareaVoluntarios(this,(Voluntario) usuario);
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFichar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaTareas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTareas;
    // End of variables declaration//GEN-END:variables
}
