/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.FachadaAplicacion;
import aplicacion.Producto;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
/**
 *
 * @author alumnogreibd
 */
public class VTiendas extends javax.swing.JDialog {
    private boolean nuevo;
    private FachadaAplicacion fa;
    private int numSucursal;
    /**
     * Creates new form VTiendas
     */
    public VTiendas(java.awt.Frame parent, boolean modal, FachadaAplicacion fa, int numSucursal) {
        super(parent, modal);
        getContentPane().setBackground(new Color(200,199,196));
        this.numSucursal=numSucursal;
        this.fa=fa;
        initComponents();
        buscarTiendas();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTiendaText = new javax.swing.JTextField();
        nombreProductoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        numExistenciasText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscarTiendasbtn = new javax.swing.JButton();
        nuevobtn = new javax.swing.JButton();
        guardarbtn = new javax.swing.JButton();
        borrarbtn = new javax.swing.JButton();
        buscarProductosbtn = new javax.swing.JButton();
        eliminarProductobtn = new javax.swing.JButton();
        guardarProductobtn = new javax.swing.JButton();
        anadirProductobtn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTiendas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(200, 199, 196));

        jLabel1.setText("Nombre Tienda:");

        jLabel2.setText("Nombre Producto:");

        jLabel3.setText("nombre:");

        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });

        jLabel4.setText("nº existencias:");

        buscarTiendasbtn.setText("Buscar");
        buscarTiendasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTiendasbtnActionPerformed(evt);
            }
        });

        nuevobtn.setText("Nuevo");
        nuevobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobtnActionPerformed(evt);
            }
        });

        guardarbtn.setText("Guardar");
        guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtnActionPerformed(evt);
            }
        });

        borrarbtn.setText("Borrar");
        borrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbtnActionPerformed(evt);
            }
        });

        buscarProductosbtn.setText("Buscar");
        buscarProductosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductosbtnActionPerformed(evt);
            }
        });

        eliminarProductobtn.setText("Eliminar Producto");
        eliminarProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductobtnActionPerformed(evt);
            }
        });

        guardarProductobtn.setText("Guardar");
        guardarProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProductobtnActionPerformed(evt);
            }
        });

        anadirProductobtn.setText("Añadir producto");
        anadirProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirProductobtnActionPerformed(evt);
            }
        });

        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        tablaTiendas.setModel(new ModeloTablaTiendas());
        tablaTiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTiendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTiendas);

        tablaProductos.setModel(new ModeloTablaProductosTienda());
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombreProductoText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buscarProductosbtn)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreTiendaText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buscarTiendasbtn)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nuevobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(guardarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(borrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(numExistenciasText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(eliminarProductobtn, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(anadirProductobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(guardarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(25, 25, 25)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreTiendaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTiendasbtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevobtn)
                            .addComponent(guardarbtn)
                            .addComponent(borrarbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreProductoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProductosbtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numExistenciasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarProductobtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anadirProductobtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(guardarProductobtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTiendasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTiendasbtnActionPerformed
        // TODO add your handling code here:
        buscarTiendas();
    }//GEN-LAST:event_buscarTiendasbtnActionPerformed

    private void guardarProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProductobtnActionPerformed
        // TODO add your handling code here:
        ModeloTablaTiendas m;
        m=(ModeloTablaTiendas) tablaTiendas.getModel();
        ModeloTablaProductosTienda m2;
        m2=(ModeloTablaProductosTienda) tablaProductos.getModel();
        fa.actualizarProductoTienda( m.obtenerTienda(tablaTiendas.getSelectedRow()).getNombre(), m2.obtenerProducto(tablaProductos.getSelectedRow()).getNombre(),  Integer.parseInt(numExistenciasText.getText()),  numSucursal);
        buscarProducto();
    }//GEN-LAST:event_guardarProductobtnActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void nuevobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobtnActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        tablaTiendas.clearSelection();
        ModeloTablaProductosTienda m;
        m=(ModeloTablaProductosTienda) tablaProductos.getModel();
        m.setFilas(new ArrayList<Producto>());
        this.nuevo=true;
        borrarbtn.setEnabled(false);
        guardarProductobtn.setEnabled(false);
        eliminarProductobtn.setEnabled(false);
        numExistenciasText.setText("");
        nombreText.setText("");
    }//GEN-LAST:event_nuevobtnActionPerformed

    private void borrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbtnActionPerformed
        // TODO add your handling code here:
        ModeloTablaTiendas m;
        m=(ModeloTablaTiendas) tablaTiendas.getModel();
        fa.eliminarTienda(m.obtenerTienda(tablaTiendas.getSelectedRow()).getNombre(),numSucursal);
        buscarTiendas();
    }//GEN-LAST:event_borrarbtnActionPerformed

    private void guardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtnActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        if (nuevo==true){
            fa.nuevaTienda(nombreText.getText(), numSucursal);
        }
        else{
            ModeloTablaTiendas m;
            m=(ModeloTablaTiendas) tablaTiendas.getModel();
            fa.actualizarTienda(m.obtenerTienda(tablaTiendas.getSelectedRow()).getNombre(),nombreText.getText(),numSucursal);
        }
        buscarTiendas();
    }//GEN-LAST:event_guardarbtnActionPerformed

    private void eliminarProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductobtnActionPerformed
        // TODO add your handling code here:
        ModeloTablaTiendas m;
        m=(ModeloTablaTiendas) tablaTiendas.getModel();
        ModeloTablaProductosTienda m2;
        m2=(ModeloTablaProductosTienda) tablaProductos.getModel();
        fa.eliminarProductoTienda( m.obtenerTienda(tablaTiendas.getSelectedRow()).getNombre(), m2.obtenerProducto(tablaProductos.getSelectedRow()).getNombre(),  numSucursal);
        buscarProducto();
    }//GEN-LAST:event_eliminarProductobtnActionPerformed

    private void buscarProductosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductosbtnActionPerformed
        // TODO add your handling code here:
        buscarProducto();
    }//GEN-LAST:event_buscarProductosbtnActionPerformed

    private void anadirProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirProductobtnActionPerformed
        // TODO add your handling code here:
        ModeloTablaTiendas m;
        m=(ModeloTablaTiendas) tablaTiendas.getModel();
        fa.abrirVProductosTienda(m.obtenerTienda(tablaTiendas.getSelectedRow()).getNombre(),numSucursal);
    }//GEN-LAST:event_anadirProductobtnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tablaTiendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTiendasMouseClicked
        // TODO add your handling code here:
        ConfigurarInfoTiendaSelecionada();
    }//GEN-LAST:event_tablaTiendasMouseClicked

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
        ConfigurarInfoProductoSelecionado();
    }//GEN-LAST:event_tablaProductosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirProductobtn;
    private javax.swing.JButton borrarbtn;
    private javax.swing.JButton buscarProductosbtn;
    private javax.swing.JButton buscarTiendasbtn;
    private javax.swing.JButton eliminarProductobtn;
    private javax.swing.JButton guardarProductobtn;
    private javax.swing.JButton guardarbtn;
    private javax.swing.JButton jButton9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreProductoText;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField nombreTiendaText;
    private javax.swing.JButton nuevobtn;
    private javax.swing.JTextField numExistenciasText;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaTiendas;
    // End of variables declaration//GEN-END:variables



    private void ConfigurarInfoTiendaSelecionada(){
        this.nuevo=false;
        borrarbtn.setEnabled(true);
        ModeloTablaTiendas m;
        m=(ModeloTablaTiendas) tablaTiendas.getModel();
        nombreText.setText((String)m.getValueAt(tablaTiendas.getSelectedRow(),0));
        buscarProducto();
}
    
 private void buscarTiendas(){
        ModeloTablaTiendas m;
        m=(ModeloTablaTiendas) tablaTiendas.getModel();
        m.setFilas(fa.obtenerTiendas(nombreTiendaText.getText(), numSucursal));
        
        if (m.getRowCount()> 0) {
            tablaTiendas.setRowSelectionInterval(0, 0);
            ConfigurarInfoTiendaSelecionada();
            guardarbtn.setEnabled(true);
            borrarbtn.setEnabled(true);
            anadirProductobtn.setEnabled(true);
            buscarProducto();
        }
        else {
            this.nuevo=false;
            nombreTiendaText.setText("");
            guardarbtn.setEnabled(false);
            borrarbtn.setEnabled(false);
            guardarProductobtn.setEnabled(false);
            eliminarProductobtn.setEnabled(false);
            anadirProductobtn.setEnabled(false);
            ModeloTablaProductosTienda m2;
            m2=(ModeloTablaProductosTienda) tablaProductos.getModel();
            m2.setFilas(new ArrayList<Producto>());
        }
        
    }    
 
 
 
    private void ConfigurarInfoProductoSelecionado(){
        this.nuevo=false;
        borrarbtn.setEnabled(true);
        ModeloTablaProductosTienda m;
        m=(ModeloTablaProductosTienda) tablaProductos.getModel();
        numExistenciasText.setText(String.valueOf((m.obtenerProducto(tablaProductos.getSelectedRow())).getUnidades()));
}
    
 private void buscarProducto(){
        ModeloTablaProductosTienda m;
        m=(ModeloTablaProductosTienda) tablaProductos.getModel();
        ModeloTablaTiendas m2;
        m2=(ModeloTablaTiendas) tablaTiendas.getModel();
        m.setFilas(fa.obtenerProductosTienda((String)m2.getValueAt(tablaTiendas.getSelectedRow(),0), numSucursal, nombreProductoText.getText()));
        
        if (m.getRowCount()> 0) {
            tablaProductos.setRowSelectionInterval(0, 0);
            ConfigurarInfoProductoSelecionado();
            eliminarProductobtn.setEnabled(true);
            guardarProductobtn.setEnabled(true);
        }
        else {
            this.nuevo=false;
            numExistenciasText.setText("");
            guardarProductobtn.setEnabled(false);
            eliminarProductobtn.setEnabled(false);
        }
    }  
    
    
}
