/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Cliente;
import aplicacion.FachadaAplicacion;
import aplicacion.Personal;
import aplicacion.Usuario;
import aplicacion.Voluntario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import java.text.SimpleDateFormat;
import java.sql.Time;
/**
 *
 * @author alumnogreibd
 */
public class VUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VUsuarios
     */
    aplicacion.FachadaAplicacion fa;
    Usuario usuario;
    boolean nuevo;
    
    public VUsuarios(aplicacion.FachadaAplicacion fa, Usuario usuario) {
        this.fa = fa;
        this.usuario = usuario;
        this.setContentPane(new Fondo());
        initComponents();
        nuevo=false;
        cbTipo.setEnabled(false);
        
        cbTipo.setSelectedItem("Personal");
        ModeloTablaUsuarios mtu = new ModeloTablaUsuarios();
        tbUsuarios.setModel(mtu);
        tbUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tbUsuarios.getSelectionModel().addListSelectionListener((lse) -> {
            int index = tbUsuarios.getSelectedRow();
            if(index < 0)
                return;
            nuevo=false;
            cbTipo.setEnabled(false);
            Usuario usr = mtu.obtenerUsuario(index);
            NombreText.setText(usr.getNombre());
            DNIText.setText(usr.getDni());
            DireccionText.setText(usr.getDireccion());
            TelefonoText.setText(String.valueOf(usr.getTelefono()));
            EmailText.setText(usr.getEmail());
            ClaveText.setText(usr.getClave());
            
            
            
            if(usr instanceof aplicacion.Cliente) {
                
                cbTipo.setSelectedItem("Cliente");
                PuntuacionText.setText(String.valueOf(((Cliente) usr).getPuntuacion()));
            }
            
            if(usr instanceof aplicacion.Voluntario) {
               
                cbTipo.setSelectedItem("Voluntario");
                HoraEntradaText.setText(((Voluntario) usr).getHoraEntrada().toString());
                HoraSalidaText.setText(((Voluntario) usr).getHoraSalida().toString());
            }
            
            if(usr instanceof aplicacion.Personal) {
                cbTipo.setSelectedItem("Personal");
                HoraEntradaText.setText(((Personal) usr).getHoraEntrada().toString());
                HoraSalidaText.setText(((Personal) usr).getHoraSalida().toString());
                CargoText.setText(((Personal) usr).getCargo());
                EBANText.setText(((Personal) usr).getCuentaBancaria());
            }
        });
        /*if(usuario instanceof aplicacion.Cliente) {
            hentradalb.setVisible(false);
            hsalidalb.setVisible(false);
            HoraSalidaText.setVisible(false);
            HoraEntradaText.setVisible(false);
            HoraSalidaText.setEnabled(false);
            HoraEntradaText.setEnabled(false);
            cargolb.setVisible(false);
            CargoText.setVisible(false);
            CargoText.setEnabled(false);
            ebanlb.setVisible(false);
            EBANText.setEnabled(false);
            btnNuevo.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnGuardar.setEnabled(false);
        }*/
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DNITextB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NombreTextB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreText = new javax.swing.JTextField();
        DNIText = new javax.swing.JTextField();
        DireccionText = new javax.swing.JTextField();
        TelefonoText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        puntuacionlb = new javax.swing.JLabel();
        hentradalb = new javax.swing.JLabel();
        hsalidalb = new javax.swing.JLabel();
        cargolb = new javax.swing.JLabel();
        ebanlb = new javax.swing.JLabel();
        PuntuacionText = new javax.swing.JTextField();
        HoraEntradaText = new javax.swing.JTextField();
        HoraSalidaText = new javax.swing.JTextField();
        CargoText = new javax.swing.JTextField();
        EBANText = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        ClaveText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI:");

        jLabel2.setText("Nombre:");

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbUsuarios);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre: ");

        jLabel4.setText("DNI:      ");

        jLabel5.setText("Tipo:     ");

        jLabel6.setText("Dirección:");

        jLabel7.setText("Teléfono:");

        jLabel8.setText("Email: ");

        TelefonoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoTextActionPerformed(evt);
            }
        });

        puntuacionlb.setText("Puntuacion:");

        hentradalb.setText("Hora entrada:");

        hsalidalb.setText("Hora salida:");

        cargolb.setText("Cargo:");

        ebanlb.setText("EBAN:");

        EBANText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBANTextActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Voluntario", "Personal" }));
        cbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoItemStateChanged(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Clave:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DireccionText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNIText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(puntuacionlb)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hsalidalb)
                            .addComponent(hentradalb)))
                    .addComponent(cargolb)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(ebanlb))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PuntuacionText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(HoraSalidaText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(HoraEntradaText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(EBANText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(CargoText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(ClaveText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(EmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DNITextB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NombreTextB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnGuardar)))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DNITextB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(NombreTextB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnBorrar)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(NombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(DNIText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DireccionText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TelefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(puntuacionlb)
                                            .addComponent(PuntuacionText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HoraEntradaText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hentradalb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HoraSalidaText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hsalidalb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CargoText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cargolb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EBANText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ebanlb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(ClaveText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        List<Usuario> usrs = fa.buscarUsuarios(DNITextB.getText(), NombreTextB.getText());
        CargoText.setText("");
        DNIText.setText("");
        DNITextB.setText("");
        DireccionText.setText("");
        EBANText.setText("");
        EmailText.setText("");
        HoraEntradaText.setText("");
        HoraSalidaText.setText("");
        NombreText.setText("");
        NombreTextB.setText("");
        PuntuacionText.setText("");
        TelefonoText.setText("");
        ClaveText.setText("");
        ((ModeloTablaUsuarios)tbUsuarios.getModel()).setFilas(usrs);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int index = tbUsuarios.getSelectedRow();
        if(index < 0) return;
        
        String dni = (String)tbUsuarios.getValueAt(index, 1);
        
        int result = fa.eliminarUsuario(dni);
        
        if(result > 0)
            ((ModeloTablaUsuarios)tbUsuarios.getModel()).eliminarUsuario(index);
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void EBANTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBANTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EBANTextActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        nuevo=true;
        cbTipo.setEnabled(true);
        tbUsuarios.clearSelection();
        
        CargoText.setText("");
        DNIText.setText("");
        DNITextB.setText("");
        DireccionText.setText("");
        EBANText.setText("");
        EmailText.setText("");
        HoraEntradaText.setText("");
        HoraSalidaText.setText("");
        NombreText.setText("");
        NombreTextB.setText("");
        PuntuacionText.setText("");
        TelefonoText.setText("");
        ClaveText.setText("");
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoItemStateChanged
        // TODO add your handling code here:
        
        PuntuacionText.setEnabled(true);
        HoraSalidaText.setEnabled(true);
        HoraEntradaText.setEnabled(true);
        CargoText.setEnabled(true);
        EBANText.setEnabled(true);
        if (cbTipo.getSelectedItem()=="Cliente"){
            HoraSalidaText.setEnabled(false);
            HoraEntradaText.setEnabled(false);
            CargoText.setEnabled(false);
            EBANText.setEnabled(false);
            HoraSalidaText.setText("");
            HoraEntradaText.setText("");
            CargoText.setText("");
            EBANText.setText("");
    }
        else if (cbTipo.getSelectedItem()=="Voluntario"){
            PuntuacionText.setEnabled(false);
            CargoText.setEnabled(false);
            EBANText.setEnabled(false);

            PuntuacionText.setText("");
            CargoText.setText("");
            EBANText.setText("");
        }
        else{
            PuntuacionText.setEnabled(false);
            PuntuacionText.setText("");
        }
    }//GEN-LAST:event_cbTipoItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       
        if (nuevo==true){
            Usuario nuevoUsuario;
            if (cbTipo.getSelectedItem()=="Voluntario"){
                nuevoUsuario= new Voluntario(DNIText.getText(),ClaveText.getText(),NombreText.getText(),
                        DireccionText.getText(),EmailText.getText(),Integer.parseInt(TelefonoText.getText()),
                        Time.valueOf(HoraEntradaText.getText()),Time.valueOf(HoraSalidaText.getText()));
            }
            else if (cbTipo.getSelectedItem()=="Personal"){
                nuevoUsuario=new Personal(DNIText.getText(),ClaveText.getText(),NombreText.getText(),
                        DireccionText.getText(),EmailText.getText(),Integer.parseInt(TelefonoText.getText()),CargoText.getText(),
                        Time.valueOf(HoraEntradaText.getText()),Time.valueOf(HoraSalidaText.getText()),EBANText.getText());
            }
            else{
                nuevoUsuario=new Cliente(DNIText.getText(),ClaveText.getText(),NombreText.getText(),
                        DireccionText.getText(),EmailText.getText(),Integer.parseInt(TelefonoText.getText()),
                        Integer.parseInt(PuntuacionText.getText()));
            }
                  
            fa.nuevoUsuario(nuevoUsuario);
            btnBuscar.doClick();
            cbTipo.setEnabled(false);
        }
        else {
            int index = tbUsuarios.getSelectedRow();
            if(index < 0) return;

            String dniAnterior = (String)tbUsuarios.getValueAt(index, 1);
            Usuario usuarioActualizado;
            if (cbTipo.getSelectedItem()=="Voluntario"){
                usuarioActualizado= new Voluntario(DNIText.getText(),ClaveText.getText(),NombreText.getText(),
                        DireccionText.getText(),EmailText.getText(),Integer.parseInt(TelefonoText.getText()),
                        Time.valueOf(HoraEntradaText.getText()),Time.valueOf(HoraSalidaText.getText()));
            }
            else if (cbTipo.getSelectedItem()=="Personal"){
                usuarioActualizado=new Personal(DNIText.getText(),ClaveText.getText(),NombreText.getText(),
                        DireccionText.getText(),EmailText.getText(),Integer.parseInt(TelefonoText.getText()),CargoText.getText(),
                        Time.valueOf(HoraEntradaText.getText()),Time.valueOf(HoraSalidaText.getText()),EBANText.getText());
            }
            else{
                usuarioActualizado=new Cliente(DNIText.getText(),ClaveText.getText(),NombreText.getText(),
                        DireccionText.getText(),EmailText.getText(),Integer.parseInt(TelefonoText.getText()),
                        Integer.parseInt(PuntuacionText.getText()));
            }
            fa.actualizarUsuario(dniAnterior,usuarioActualizado);
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void TelefonoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CargoText;
    private javax.swing.JTextField ClaveText;
    private javax.swing.JTextField DNIText;
    private javax.swing.JTextField DNITextB;
    private javax.swing.JTextField DireccionText;
    private javax.swing.JTextField EBANText;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField HoraEntradaText;
    private javax.swing.JTextField HoraSalidaText;
    private javax.swing.JTextField NombreText;
    private javax.swing.JTextField NombreTextB;
    private javax.swing.JTextField PuntuacionText;
    private javax.swing.JTextField TelefonoText;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel cargolb;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel ebanlb;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel hentradalb;
    private javax.swing.JLabel hsalidalb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel puntuacionlb;
    private javax.swing.JTable tbUsuarios;
    // End of variables declaration//GEN-END:variables
}
